import { Dispatch, SetStateAction, createContext, useState } from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { APIResponse } from './result/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'FitAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className} py-8 flex flex-col items-center`}>
        {children}
      </body>
    </html>
  );
}
